if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_bts_group',
		'title' => 'bts_group',
		'fields' => array (
			array (
				'key' => 'field_5b033ff10e5b5',
				'label' => 'キャッチコピー',
				'name' => 'comment',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0340430e5b6',
				'label' => '種類',
				'name' => 'usage',
				'type' => 'taxonomy',
				'taxonomy' => 'bt_usage_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0541ad4309d',
				'label' => '分類',
				'name' => 'category',
				'type' => 'taxonomy',
				'taxonomy' => 'bt_goods_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0344db0e5bf',
				'label' => 'メーカー',
				'name' => 'maker',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345040e5c0',
				'label' => 'メーカー型式',
				'name' => 'maker_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0341e20e5ba',
				'label' => '本体価格（税抜）',
				'name' => 'price',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0342480e5bc',
				'label' => '商品写真',
				'name' => 'photo',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b0343390e5bd',
				'label' => '360度パノラマ写真',
				'name' => 'panorama',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b03437a0e5be',
				'label' => '紹介動画',
				'name' => 'youtube',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b03451a0e5c1',
				'label' => '商品コード',
				'name' => 'code',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03407a0e5b7',
				'label' => '作業床高さ',
				'name' => 'height',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0340f80e5b8',
				'label' => '高さで探す',
				'name' => 'height_range',
				'type' => 'taxonomy',
				'taxonomy' => 'bt_height_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0341a40e5b9',
				'label' => '寸法（外寸：mm）',
				'name' => 'lwh',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b040250e3b26',
				'label' => '積載荷重（Kg)',
				'name' => 'load_weight',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0402b9d501e',
				'label' => '駆動方法',
				'name' => 'method',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03455c0e5c3',
				'label' => '本体重量(kg)',
				'name' => 'weight',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0345a00e5c4',
				'label' => '年式',
				'name' => 'y_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345d60e5c5',
				'label' => '状態',
				'name' => 'status',
				'type' => 'taxonomy',
				'taxonomy' => 'status_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0346030e5c6',
				'label' => '保有場所',
				'name' => 'stock_point',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'shops',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0542f5bd81d',
				'label' => '数量',
				'name' => 'amount',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0346d80e5c7',
				'label' => 'お問合わせ',
				'name' => 'req',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'shops',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b03473a0e5c8',
				'label' => '電話',
				'name' => 'tel',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03475f0e5c9',
				'label' => '担当者',
				'name' => 'staff',
				'type' => 'user',
				'role' => array (
					0 => 'author',
				),
				'field_type' => 'select',
				'allow_null' => 1,
			),
			array (
				'key' => 'field_5b0348410e5ca',
				'label' => '担当者コメント',
				'name' => 'staff_comment',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'bts',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_news_group',
		'title' => 'news_group',
		'fields' => array (
			array (
				'key' => 'field_5b01eb42e380b',
				'label' => '事業分類',
				'name' => 'products_cat',
				'type' => 'taxonomy',
				'required' => 1,
				'taxonomy' => 'products_cat',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'news',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_pms_group',
		'title' => 'pms_group',
		'fields' => array (
			array (
				'key' => 'field_5b033ff10e5b5',
				'label' => 'キャッチコピー',
				'name' => 'comment',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0340430e5b6',
				'label' => '種類',
				'name' => 'usage',
				'type' => 'taxonomy',
				'taxonomy' => 'bt_usage_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0344db0e5bf',
				'label' => 'メーカー',
				'name' => 'maker',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345040e5c0',
				'label' => 'メーカー型式',
				'name' => 'maker_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0342110e5bb',
				'label' => '価格で探す',
				'name' => 'price_range',
				'type' => 'taxonomy',
				'taxonomy' => 'pm_price_range_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0342480e5bc',
				'label' => '商品写真',
				'name' => 'photo',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b0343390e5bd',
				'label' => '360度パノラマ写真',
				'name' => 'panorama',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b03437a0e5be',
				'label' => '紹介動画',
				'name' => 'youtube',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b03451a0e5c1',
				'label' => '商品コード',
				'name' => 'code',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345380e5c2',
				'label' => '管理No',
				'name' => 'ctl_no',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03fce86bf07',
				'label' => 'クラス',
				'name' => 'class',
				'type' => 'taxonomy',
				'taxonomy' => 'pm_class_cat',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b03fdd08f0af',
				'label' => '仕様',
				'name' => 'spec',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03455c0e5c3',
				'label' => '本体重量(kg)',
				'name' => 'weight',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0345a00e5c4',
				'label' => '年式',
				'name' => 'y_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345d60e5c5',
				'label' => '状態',
				'name' => 'status',
				'type' => 'taxonomy',
				'taxonomy' => 'status_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0346030e5c6',
				'label' => '保有場所',
				'name' => 'stock_point',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'shops',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0346d80e5c7',
				'label' => 'お問合わせ',
				'name' => 'req',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'shops',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b03473a0e5c8',
				'label' => '電話',
				'name' => 'tel',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03475f0e5c9',
				'label' => '担当者',
				'name' => 'staff',
				'type' => 'user',
				'role' => array (
					0 => 'author',
				),
				'field_type' => 'select',
				'allow_null' => 1,
			),
			array (
				'key' => 'field_5b0348410e5ca',
				'label' => '担当者コメント',
				'name' => 'staff_comment',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'pms',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_shops_group',
		'title' => 'shops_group',
		'fields' => array (
			array (
				'key' => 'field_5b0334d95e6ed',
				'label' => '住所',
				'name' => 'address',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '郵便番号(xxx-xxxx) と 住所',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0336fc5e6ee',
				'label' => '都道府県',
				'name' => 'prefecture',
				'type' => 'taxonomy',
				'taxonomy' => 'pref_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0337475e6ef',
				'label' => '電話',
				'name' => 'tel',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'shops',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_units_group',
		'title' => 'units_group',
		'fields' => array (
			array (
				'key' => 'field_5b033ff10e5b5',
				'label' => 'キャッチコピー',
				'name' => 'comment',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0340430e5b6',
				'label' => '種類',
				'name' => 'usage',
				'type' => 'taxonomy',
				'taxonomy' => 'bt_usage_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0344db0e5bf',
				'label' => 'メーカー',
				'name' => 'maker',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345040e5c0',
				'label' => 'メーカー型式',
				'name' => 'maker_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0342110e5bb',
				'label' => '価格で探す',
				'name' => 'price_range',
				'type' => 'taxonomy',
				'taxonomy' => 'pm_price_range_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0342480e5bc',
				'label' => '商品写真',
				'name' => 'photo',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b0343390e5bd',
				'label' => '360度パノラマ写真',
				'name' => 'panorama',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b03437a0e5be',
				'label' => '紹介動画',
				'name' => 'youtube',
				'type' => 'file',
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5b03451a0e5c1',
				'label' => '商品コード',
				'name' => 'code',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345380e5c2',
				'label' => '管理No',
				'name' => 'ctl_no',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0340f80e5b8',
				'label' => '高さで探す',
				'name' => 'height_range',
				'type' => 'taxonomy',
				'taxonomy' => 'bt_height_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0341a40e5b9',
				'label' => '寸法（外寸：mm）',
				'name' => 'lwh',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b03455c0e5c3',
				'label' => '本体重量(kg)',
				'name' => 'weight',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5b0345a00e5c4',
				'label' => '年式',
				'name' => 'y_type',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b0345d60e5c5',
				'label' => '状態',
				'name' => 'status',
				'type' => 'taxonomy',
				'taxonomy' => 'status_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0346030e5c6',
				'label' => '保有場所',
				'name' => 'stock_point',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'shops',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b0346d80e5c7',
				'label' => 'お問合わせ',
				'name' => 'req',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'shops',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b03473a0e5c8',
				'label' => '電話',
				'name' => 'tel',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b465a83851e4',
				'label' => '販促ラベル',
				'name' => 'mark_label',
				'type' => 'taxonomy',
				'taxonomy' => 'mark_label_cat',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'object',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b465ce0324f6',
				'label' => '都道府県',
				'name' => 'pref',
				'type' => 'taxonomy',
				'taxonomy' => 'pref_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b465d3f324f7',
				'label' => '所属販売エリア',
				'name' => 'sales_area',
				'type' => 'taxonomy',
				'taxonomy' => 'shop_sales_area_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_5b465dc6324f8',
				'label' => '所属都道府県エリア',
				'name' => 'pref_area',
				'type' => 'taxonomy',
				'taxonomy' => 'shop_pref_area_cat',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'units',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

